%% setLed
% Set the small green LED on Engduino to turn on/off
%
%% Syntax
e.setLed(val);
%% Description
% <html>
% <head>
% <link rel="stylesheet" href="../css/style.css">
% </head>
% <table style="width: 100%" >
%   <tr>
%      <td style="width:40%"><a href="#one">e.setLed(1)</a></td>
%      <td>Turn on the small LED on Engduino</td> 
%   </tr>
%   <tr>
%      <td style="width:40%"><a href="#one">e.setLed(0)</a></td>
%      <td>Turn off the small LED on Engduino</td> 
%   </tr>
%   <tr>
%      <td style="width:40%"><a href="#two">int e.setLed(vals)</a></td>
%      <td>Turn on/off the small LED on Engduino with return status</td> 
%   </tr>
% </table>
% </html>
% 
%% Examples
%
% <html>
% <a name="one" id="title"><li><b>Turn on the small green LED on Engduino</b></li></a>
% </html>
%
% Connect to Engduino on port 3 and set the LED on

% Check if the Engduino object already exists. Otherwise initialize it.
if (~exist('e', 'var'))
        e = engduino();
end
e.setLed(1);

%%
%
% <html>
% <a name="two" id="title"><li><b>Get return status of whether the setLed() command has been executed successfully</b></li></a>
% </html>
%
% Connect to Engduino on port 3 and set the LED on, return the status code
% generated by executing the command.

% Check if the Engduino object already exists. Otherwise initialize it.
if (~exist('e', 'var'))
        e = engduino();
end
res = e.setLed(1);

%% Input Arguments
%
% <html>
% <table style="width: 100%" >
%   <tr>
%      <td style="width:30%">vals</td>
%      <td>(int) 0:turn off LED, 1:turn on LED</td> 
%   </tr>
% </table>
% </html>
% 
%% Output Arguments
% 
% <html>
% <table style="width: 100%" >
%   <tr>
%      <td style="width:30%">res</td>
%      <td>Return status to indicate whether function has been executed (int) 0: OK, <0: Error code</td> 
%   </tr>
% </table>
% </html>
