%% setLeds
% Set individual colours of all the 16 LEDs on Engduino
%
%% Syntax
e.setLeds(vals);
%% Description
% <html>
% <head>
% <link rel="stylesheet" href="../css/style.css">
% </head>
% <table style="width: 100%" >
%   <tr>
%      <td id="api"><a href="#one">e.setLeds(vals[1-16])</a></td>
%      <td>Set individual colours of all the 16 LEDs on Engduino</td> 
%   </tr>
%   <tr>
%      <td id="api"><a href="#two">int e.setLeds(vals[1-16])</a></td>
%      <td>Set individual colours of all the 16 LEDs on Engduino with return status</td> 
%   </tr>
% </table>
% </html>
% 
%% Examples
%
% <html>
% <a name="one" id="title"><li><b>Set individual colours of all the 16 LEDs on Engduino using the Colour properties</b></li></a>
% </html>
%
% Connect to Engduino on port 3 and set individual colours of all the 16
% LEDs on Engduino using Colour properties

% Colours are defined in engduino object as:
%     COLOR_RED =     0
%     COLOR_GREEN =   1
%     COLOR_BLUE =    2
%     COLOR_YELLOW =  3
%     COLOR_MAGENTA = 4
%     COLOR_CYA =     5
%     COLOR_WHITE =   6
%     COLOR_OFF =     7

% Check if the Engduino object already exists. Otherwise initialize it.
if (~exist('e', 'var'))
        e = engduino();
end
e.setLeds([e.COLOR_RED, e.COLOR_GREEN, e.COLOR_BLUE, e.COLOR_YELLOW, ...
           e.COLOR_MAGENTA, e.COLOR_CYA, e.COLOR_WHITE, e.COLOR_OFF, ...
           e.COLOR_RED, e.COLOR_GREEN, e.COLOR_BLUE, e.COLOR_YELLOW, ...
           e.COLOR_MAGENTA, e.COLOR_CYA, e.COLOR_WHITE, e.COLOR_OFF]);

%%
%
% <html>
% <a name="two" id="title"><li><b>Get return status of whether the setLeds() command has been executed successfully</b></li></a>
% </html>
%
% Connect to Engduino on port 3 and set individual colours of all the 16
% LEDs on Engduino using integers [0-7], return the status code
% generated by executing the command.


% Check if the Engduino object already exists. Otherwise initialize it.
if (~exist('e', 'var'))
        e = engduino();
end
res = e.setLeds([1, 2, 3, 4, ...
                 5, 0, 1, 2, ...
                 6, 7, 2, 3, ...
                 1, 2, 3, 4]);
             
%% Input Arguments
%
% <html>
% <table style="width: 100%" >
%   <tr>
%      <td id="api">vals[1-16]</td>
%      <td> A 1x16 Matrix [color1,...,color16] with colour values
% correspond to the Engduino LEDs </td> 
%   </tr>
% </table>
% </html>
% 
%% Output Arguments
% 
% <html>
% <table style="width: 100%" >
%   <tr>
%      <td id="api">res</td>
%      <td>Return status to indicate whether function has been executed (int) 0: OK, <0: Error code</td> 
%   </tr>
% </table>
% </html>
%% Properties
% * <../engduino_leds.html#colour_properties LED Colours>
%



